### ISSUE TITLE
Slash command support

### ISSUE THREAD

**Issue by spenat28** [Tamako-Tech/Tamako#1]
What about slash command support? It would be much more convenient ...

**Comment by BearTS** [comment]
The current version is in development, even tho the public repository has not been updated yet 
but it is being actively developed, and the new update is almost ready to be pushed to devlopment asap we are done with testing
And once that's done, I will push the current build with some changes (to make some features exclusive to the bot), to make it publically available

Now a bit about the roadmap, 
Yes, slash commands are expected to be included as soon as I complete porting the previous commands to d.js v13 and then will start working on Slash commands as well as context menus and much more.
If you would like to participate in testing, join the support server at https://support.tamako.tech/

Let me know if you have more doubts

**Comment by spenat28** [comment]
Thanks for update.

I would also appreciate to change prefix of the bot when using your instance of the bot.

**Comment by BearTS** [comment]
> I would also appreciate to change prefix of the bot when using your instance of the bot.

As of now, I do not have that planned, due to various internal issues, but maybe in a future update, we might be able to see such feature, Let's see
